### ISSUE TITLE
New hooks breaks normal describe tests.

### ISSUE THREAD

**Issue by CaptainJiNX** [iensu/mocha-cakes-2#17]
If you run this with version 3.1.0, it will crash... 3.0.0 worked fine before.

```
'use strict';

describe('everything', () => {
  it('should work', () => {
    true.should.equal.true;
  });
});
```

**Comment by iensu** [comment]
Thank you for reporting and fixing this! Your fix has been merged and released, so closing this! :)

**Comment by meis** [comment]
Quite ashamed this happened, thanks for fixing it, @CaptainJiNX !

**Comment by CaptainJiNX** [comment]
No need to be ashamed, it was just a simple bug. :)

**Comment by iensu** [comment]
@meis, not on you. I should have checked the PR better. Thought I had things covered in the tests 🤦‍♂️
