### ISSUE TITLE
Data driven testing?

### ISSUE THREAD

**Issue by kunalmalviya** [iensu/mocha-cakes-2#7]
Hi,

Is it possible to create data driven tests with this library? I am using this with chakram and would like to avoid creating multiple test cases for same same assertion. Any examples? Thanks,

**Comment by iensu** [comment]
Hi @kunalmalviya!

Could you give me a concrete example of what you mean? I assume it's something like the code below, but correct me if I'm wrong:

``` javascript
listOfTestData.forEach((testData) => {
   scenario(`Testing ${testData.description}`, () => {
      given(...);
      ...
   });
});
```

That should work fine. I've done similar things like that in plain mocha and there should be no difference. Please tell me if you encounter any issues.

**Comment by kunalmalviya** [comment]
Thank you. It seems I was able to make it work.

**Comment by iensu** [comment]
Ok great! I'll close this issue then! :)
